import { ui } from './ui.js';
export interface Env {
  DB: D1Database;
  INSTANCE_SECRET_KEY: string;
  ADMIN_TOKEN: string;
}

type HookRow = { id: string; name: string; owner: string; repo: string; discord_url: string; github_secret: string; enabled: number; created_at: string; updated_at: string };
const json = (value: unknown, status = 200) => Response.json(value, { status, headers: { 'cache-control': 'no-store' } });
const encoder = new TextEncoder();
const decoder = new TextDecoder();
const b64 = (bytes: Uint8Array) => btoa(String.fromCharCode(...bytes));
const unb64 = (value: string) => Uint8Array.from(atob(value), (c) => c.charCodeAt(0));
const now = () => new Date().toISOString();

function safeEqual(a: string, b: string) { if (a.length !== b.length) return false; let n = 0; for (let i = 0; i < a.length; i++) n |= a.charCodeAt(i) ^ b.charCodeAt(i); return n === 0; }
async function key(secret: string) { return crypto.subtle.importKey('raw', await crypto.subtle.digest('SHA-256', encoder.encode(secret)), 'AES-GCM', false, ['encrypt', 'decrypt']); }
async function seal(value: string, secret: string) { const iv = crypto.getRandomValues(new Uint8Array(12)); const data = new Uint8Array(await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, await key(secret), encoder.encode(value))); return `${b64(iv)}.${b64(data)}`; }
async function open(value: string, secret: string) { const [iv, data] = value.split('.'); if (!iv || !data) throw new Error('bad ciphertext'); return decoder.decode(await crypto.subtle.decrypt({ name: 'AES-GCM', iv: unb64(iv) }, await key(secret), unb64(data))); }
async function validSignature(body: ArrayBuffer, header: string | null, secret: string) { if (!header?.startsWith('sha256=')) return false; const k = await crypto.subtle.importKey('raw', encoder.encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']); const digest = new Uint8Array(await crypto.subtle.sign('HMAC', k, body)); return safeEqual(`sha256=${[...digest].map((x) => x.toString(16).padStart(2, '0')).join('')}`, header); }
function discordUrl(value: unknown): string | null { if (typeof value !== 'string') return null; try { const u = new URL(value); return u.protocol === 'https:' && u.hostname === 'discord.com' && /^\/api\/webhooks\/[^/]+\/[^/]+/.test(u.pathname) ? u.toString() : null; } catch { return null; } }
function text(value: unknown, max = 120) { return typeof value === 'string' && value.trim() && value.length <= max ? value.trim() : null; }
function repoPart(value: unknown) { return typeof value === 'string' && /^[A-Za-z0-9_.-]{1,100}$/.test(value) ? value : null; }
function publicHook(row: HookRow) { return { id: row.id, name: row.name, owner: row.owner, repo: row.repo, enabled: Boolean(row.enabled), created_at: row.created_at, updated_at: row.updated_at, endpoint: `/webhooks/${row.id}` }; }
function authorized(request: Request, env: Env) { return safeEqual(request.headers.get('authorization') ?? '', `Bearer ${env.ADMIN_TOKEN}`); }
function payload(event: string, input: any) { const repo = input.repository?.full_name ?? 'unknown repository'; const title = event === 'push' ? `${input.commits?.length ?? 0} commit(s) pushed to ${String(input.ref ?? '').replace('refs/heads/', '')}` : event === 'pull_request' ? `PR #${input.number ?? ''} ${input.action ?? 'updated'}: ${input.pull_request?.title ?? ''}` : `Issue #${input.issue?.number ?? ''} ${input.action ?? 'updated'}: ${input.issue?.title ?? ''}`; const url = event === 'push' ? input.compare : event === 'pull_request' ? input.pull_request?.html_url : input.issue?.html_url; return { username: 'RepoRadar', embeds: [{ title: title.slice(0, 256), url, color: 5793266, author: { name: input.sender?.login ?? 'GitHub' }, footer: { text: repo }, timestamp: now() }] }; }
async function readJson(request: Request) { try { return await request.json() as Record<string, unknown>; } catch { return null; } }

type DeliveryRow = { id: string; hook_id: string; github_delivery: string; event: string; payload: string; status: 'pending' | 'processing' | 'sent' | 'failed'; attempts: number; next_attempt_at: string; last_error: string | null; created_at: string; updated_at: string; sent_at: string | null };
function publicDelivery(row: DeliveryRow) { return { id: row.id, hook_id: row.hook_id, github_delivery: row.github_delivery, event: row.event, status: row.status, attempts: row.attempts, last_error: row.last_error, created_at: row.created_at, updated_at: row.updated_at, sent_at: row.sent_at }; }
function retryAt(seconds = 0) { return new Date(Date.now() + Math.max(0, seconds) * 1000).toISOString(); }
async function processDue(env: Env) { for (let i = 0; i < 10; i++) { const row = await env.DB.prepare("SELECT * FROM deliveries WHERE (status IN ('pending','failed') AND next_attempt_at<=?) OR (status='processing' AND updated_at<=?) ORDER BY created_at LIMIT 1").bind(now(), retryAt(-600)).first<DeliveryRow>(); if (!row) return; const claimed = await env.DB.prepare("UPDATE deliveries SET status='processing',updated_at=? WHERE id=? AND (status IN ('pending','failed') OR (status='processing' AND updated_at<=?))").bind(now(), row.id, retryAt(-600)).run(); if (!claimed.meta.changes) continue; const hook = await env.DB.prepare('SELECT * FROM hooks WHERE id=?').bind(row.hook_id).first<HookRow>(); if (!hook) { await env.DB.prepare("UPDATE deliveries SET status='failed',last_error=?,updated_at=? WHERE id=?").bind('hook deleted', now(), row.id).run(); continue; } let error = 'Discord delivery failed', delay = 0, sent = false; try { const response = await fetch(await open(hook.discord_url, env.INSTANCE_SECRET_KEY), { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload(row.event, JSON.parse(row.payload))) }); const responseText = await response.text(); if (response.ok) sent = true; else { error = `Discord responded ${response.status}`; if (response.status === 429) { try { delay = Number(JSON.parse(responseText).retry_after ?? 0); } catch {} delay = Math.max(delay, Number(response.headers.get('retry-after') ?? 0)); } if (response.status >= 400 && response.status < 500 && response.status !== 429) delay = -1; } } catch (cause) { error = cause instanceof Error ? cause.message.slice(0, 300) : error; } if (sent) { await env.DB.prepare("UPDATE deliveries SET status='sent',attempts=attempts+1,sent_at=?,updated_at=?,last_error=NULL WHERE id=?").bind(now(), now(), row.id).run(); continue; } const attempts = row.attempts + 1, failed = delay < 0 || attempts >= 5; await env.DB.prepare('UPDATE deliveries SET status=?,attempts=?,next_attempt_at=?,last_error=?,updated_at=? WHERE id=?').bind(failed ? 'failed' : 'pending', attempts, retryAt(delay > 0 ? delay : Math.min(300, 2 ** attempts)), error, now(), row.id).run(); } }
export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url); const path = url.pathname;
    if (request.method === 'GET' && path === '/') return new Response(ui, { headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store' } });
    if (request.method === 'GET' && path === '/healthz') return json({ status: 'ok' });
    if (path.startsWith('/api/')) {
      if (!authorized(request, env)) return json({ error: 'unauthorized' }, 401);
      if (request.method === 'GET' && path === '/api/hooks') { const rows = await env.DB.prepare('SELECT * FROM hooks ORDER BY created_at DESC').all<HookRow>(); return json({ hooks: rows.results.map(publicHook) }); }
      if (request.method === 'GET' && path === '/api/deliveries') { const rows = await env.DB.prepare('SELECT * FROM deliveries ORDER BY created_at DESC LIMIT 100').all<DeliveryRow>(); return json({ deliveries: rows.results.map(publicDelivery) }); }
      if (request.method === 'POST' && path === '/api/test-discord') { const input = await readJson(request); const discord = discordUrl(input?.discord_url); if (!discord) return json({ error: 'invalid Discord webhook URL' }, 400); try { const response = await fetch(discord, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ content: '📡 RepoRadar connection test successful.' }) }); return response.ok ? json({ ok: true }) : json({ error: 'Discord responded ' + response.status }, 400); } catch { return json({ error: 'unable to reach Discord' }, 502); } }
      const hookTest = path.match(/^\/api\/hooks\/([\w-]+)\/test$/); if (hookTest && request.method === 'POST') { const hook = await env.DB.prepare('SELECT * FROM hooks WHERE id=?').bind(hookTest[1]).first<HookRow>(); if (!hook) return json({ error: 'not found' }, 404); try { const response = await fetch(await open(hook.discord_url, env.INSTANCE_SECRET_KEY), { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ content: '📡 RepoRadar connection test successful.' }) }); return response.ok ? json({ ok: true }) : json({ error: 'Discord responded ' + response.status }, 400); } catch { return json({ error: 'unable to reach Discord' }, 502); } }
      const retry = path.match(/^\/api\/deliveries\/([\w-]+)\/retry$/); if (retry && request.method === 'POST') { const result = await env.DB.prepare("UPDATE deliveries SET status='pending',attempts=0,next_attempt_at=?,last_error=NULL,updated_at=? WHERE id=? AND status='failed'").bind(now(), now(), retry[1]).run(); if (!result.meta.changes) return json({ error: 'failed delivery not found' }, 404); ctx.waitUntil(processDue(env)); return json({ ok: true }); }
      if (request.method === 'POST' && path === '/api/hooks') {
        const input = await readJson(request); const name = text(input?.name); const owner = repoPart(input?.owner); const repo = repoPart(input?.repo); const discord = discordUrl(input?.discord_url);
        if (!name || !owner || !repo || !discord) return json({ error: 'invalid hook details' }, 400);
        const id = crypto.randomUUID(); const githubSecret = b64(crypto.getRandomValues(new Uint8Array(32))).replace(/=/g, ''); const created = now();
        await env.DB.prepare('INSERT INTO hooks (id,name,owner,repo,discord_url,github_secret,enabled,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(id, name, owner, repo, await seal(discord, env.INSTANCE_SECRET_KEY), await seal(githubSecret, env.INSTANCE_SECRET_KEY), 1, created, created).run();
        return json({ hook: { id, name, owner, repo, enabled: true, created_at: created, updated_at: created, endpoint: `/webhooks/${id}` }, github_secret: githubSecret }, 201);
      }
      const match = path.match(/^\/api\/hooks\/([\w-]+)$/);
      if (match && request.method === 'PATCH') { const input = await readJson(request); const current = await env.DB.prepare('SELECT * FROM hooks WHERE id=?').bind(match[1]).first<HookRow>(); if (!current) return json({ error: 'not found' }, 404); const name = input?.name === undefined ? current.name : text(input.name); const owner = input?.owner === undefined ? current.owner : repoPart(input.owner); const repo = input?.repo === undefined ? current.repo : repoPart(input.repo); const discord = input?.discord_url === undefined ? await open(current.discord_url, env.INSTANCE_SECRET_KEY) : discordUrl(input.discord_url); const enabled = input?.enabled === undefined ? current.enabled : input.enabled === true ? 1 : input.enabled === false ? 0 : -1; if (!name || !owner || !repo || !discord || enabled < 0) return json({ error: 'invalid hook details' }, 400); const updated = now(); await env.DB.prepare('UPDATE hooks SET name=?,owner=?,repo=?,discord_url=?,enabled=?,updated_at=? WHERE id=?').bind(name, owner, repo, await seal(discord, env.INSTANCE_SECRET_KEY), enabled, updated, current.id).run(); return json({ hook: { ...publicHook(current), name, owner, repo, enabled: Boolean(enabled), updated_at: updated } }); }
      if (match && request.method === 'DELETE') { await env.DB.prepare('DELETE FROM hooks WHERE id=?').bind(match[1]).run(); return new Response(null, { status: 204 }); }
      return json({ error: 'not found' }, 404);
    }
    const webhook = path.match(/^\/webhooks\/([\w-]+)$/);
    if (!webhook || request.method !== 'POST') return json({ error: 'not found' }, 404);
    const hook = await env.DB.prepare('SELECT * FROM hooks WHERE id=?').bind(webhook[1]).first<HookRow>();
    if (!hook || !hook.enabled) return json({ error: 'not found' }, 404);
    const body = await request.arrayBuffer(); const secret = await open(hook.github_secret, env.INSTANCE_SECRET_KEY);
    if (!await validSignature(body, request.headers.get('x-hub-signature-256'), secret)) return json({ error: 'invalid signature' }, 401);
    const event = request.headers.get('x-github-event'); if (event === 'ping') return json({ ok: true, pong: true }); if (!['push', 'pull_request', 'issues'].includes(event ?? '')) return json({ ok: true, ignored: event ?? 'unknown' }, 202);
    let input: any; try { input = JSON.parse(decoder.decode(body)); } catch { return json({ error: 'invalid JSON' }, 400); }
    if (input.repository?.owner?.login !== hook.owner || input.repository?.name !== hook.repo) return json({ error: 'repository does not match hook' }, 403);
    const delivery = request.headers.get('x-github-delivery'); if (!delivery) return json({ error: 'missing GitHub delivery ID' }, 400); const created = now(); const queued = await env.DB.prepare("INSERT INTO deliveries (id,hook_id,github_delivery,event,payload,status,attempts,next_attempt_at,created_at,updated_at) VALUES (?,?,?,?,?,'pending',0,?,?,?) ON CONFLICT(hook_id,github_delivery) DO NOTHING").bind(crypto.randomUUID(), hook.id, delivery, event, JSON.stringify(input), created, created, created).run(); if (!queued.meta.changes) return json({ ok: true, duplicate: true }, 200); ctx.waitUntil(processDue(env)); return json({ ok: true, event, queued: true }, 202);
  },
  scheduled(_event: ScheduledEvent, env: Env, ctx: ExecutionContext) { ctx.waitUntil(processDue(env)); },
} satisfies ExportedHandler<Env>;